services:
  postgres_mig:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 6666:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    name: pg_data
