amigo-folder: .amigo
debug: false
dsn: root:root@tcp(localhost:6668)/mysql
folder: migrations
json: false
package: migrations
schema-version-table: mig_schema_versions
shell-path: /bin/bash
sql: false
sql-syntax-highlighting: true
